// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: url_shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{0}
}

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_url_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_url_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type URLCreatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLCreatorRequest) Reset() {
	*x = URLCreatorRequest{}
	mi := &file_url_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLCreatorRequest) ProtoMessage() {}

func (x *URLCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLCreatorRequest.ProtoReflect.Descriptor instead.
func (*URLCreatorRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *URLCreatorRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type URLCreatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortenUrl    string                 `protobuf:"bytes,1,opt,name=shortenUrl,proto3" json:"shortenUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLCreatorResponse) Reset() {
	*x = URLCreatorResponse{}
	mi := &file_url_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLCreatorResponse) ProtoMessage() {}

func (x *URLCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLCreatorResponse.ProtoReflect.Descriptor instead.
func (*URLCreatorResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *URLCreatorResponse) GetShortenUrl() string {
	if x != nil {
		return x.ShortenUrl
	}
	return ""
}

type URLCreatorJSONRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JsonOriginalUrl string                 `protobuf:"bytes,2,opt,name=json_original_url,json=jsonOriginalUrl,proto3" json:"json_original_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *URLCreatorJSONRequest) Reset() {
	*x = URLCreatorJSONRequest{}
	mi := &file_url_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLCreatorJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLCreatorJSONRequest) ProtoMessage() {}

func (x *URLCreatorJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLCreatorJSONRequest.ProtoReflect.Descriptor instead.
func (*URLCreatorJSONRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *URLCreatorJSONRequest) GetJsonOriginalUrl() string {
	if x != nil {
		return x.JsonOriginalUrl
	}
	return ""
}

type URLCreatorJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonResult    string                 `protobuf:"bytes,1,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLCreatorJSONResponse) Reset() {
	*x = URLCreatorJSONResponse{}
	mi := &file_url_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLCreatorJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLCreatorJSONResponse) ProtoMessage() {}

func (x *URLCreatorJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLCreatorJSONResponse.ProtoReflect.Descriptor instead.
func (*URLCreatorJSONResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *URLCreatorJSONResponse) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

type URLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLRequest) Reset() {
	*x = URLRequest{}
	mi := &file_url_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLRequest) ProtoMessage() {}

func (x *URLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLRequest.ProtoReflect.Descriptor instead.
func (*URLRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *URLRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type URLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLResponse) Reset() {
	*x = URLResponse{}
	mi := &file_url_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLResponse) ProtoMessage() {}

func (x *URLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLResponse.ProtoReflect.Descriptor instead.
func (*URLResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *URLResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type URLCreatorBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*URLRequest          `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLCreatorBatchRequest) Reset() {
	*x = URLCreatorBatchRequest{}
	mi := &file_url_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLCreatorBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLCreatorBatchRequest) ProtoMessage() {}

func (x *URLCreatorBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLCreatorBatchRequest.ProtoReflect.Descriptor instead.
func (*URLCreatorBatchRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *URLCreatorBatchRequest) GetRequests() []*URLRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type URLCreatorBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*URLResponse         `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLCreatorBatchResponse) Reset() {
	*x = URLCreatorBatchResponse{}
	mi := &file_url_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLCreatorBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLCreatorBatchResponse) ProtoMessage() {}

func (x *URLCreatorBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLCreatorBatchResponse.ProtoReflect.Descriptor instead.
func (*URLCreatorBatchResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *URLCreatorBatchResponse) GetResponses() []*URLResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_url_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{12}
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_url_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_url_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserURLsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_url_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserURLsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_url_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{16}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_url_shortener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{17}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUrls     int32                  `protobuf:"varint,1,opt,name=total_urls,json=totalUrls,proto3" json:"total_urls,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_url_shortener_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{18}
}

func (x *GetStatsResponse) GetTotalUrls() int32 {
	if x != nil {
		return x.TotalUrls
	}
	return 0
}

func (x *GetStatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

var File_url_shortener_proto protoreflect.FileDescriptor

const file_url_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13url_shortener.proto\x12\x04grpc\"\a\n" +
	"\x05Empty\"!\n" +
	"\rGetURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"3\n" +
	"\x0eGetURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"6\n" +
	"\x11URLCreatorRequest\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"4\n" +
	"\x12URLCreatorResponse\x12\x1e\n" +
	"\n" +
	"shortenUrl\x18\x01 \x01(\tR\n" +
	"shortenUrl\"C\n" +
	"\x15URLCreatorJSONRequest\x12*\n" +
	"\x11json_original_url\x18\x02 \x01(\tR\x0fjsonOriginalUrl\"9\n" +
	"\x16URLCreatorJSONResponse\x12\x1f\n" +
	"\vjson_result\x18\x01 \x01(\tR\n" +
	"jsonResult\"V\n" +
	"\n" +
	"URLRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"Q\n" +
	"\vURLResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"F\n" +
	"\x16URLCreatorBatchRequest\x12,\n" +
	"\brequests\x18\x01 \x03(\v2\x10.grpc.URLRequestR\brequests\"J\n" +
	"\x17URLCreatorBatchResponse\x12/\n" +
	"\tresponses\x18\x01 \x03(\v2\x11.grpc.URLResponseR\tresponses\"\x14\n" +
	"\x12GetUserURLsRequest\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"8\n" +
	"\x13GetUserURLsResponse\x12!\n" +
	"\x04urls\x18\x01 \x03(\v2\r.grpc.UserURLR\x04urls\"+\n" +
	"\x15DeleteUserURLsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"\x18\n" +
	"\x16DeleteUserURLsResponse\"\x11\n" +
	"\x0fGetStatsRequest\"R\n" +
	"\x10GetStatsResponse\x12\x1d\n" +
	"\n" +
	"total_urls\x18\x01 \x01(\x05R\ttotalUrls\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x05R\n" +
	"totalUsers2\x96\x04\n" +
	"\fURLShortener\x123\n" +
	"\x06GetURL\x12\x13.grpc.GetURLRequest\x1a\x14.grpc.GetURLResponse\x12'\n" +
	"\x04Ping\x12\v.grpc.Empty\x1a\x12.grpc.PingResponse\x12?\n" +
	"\n" +
	"URLCreator\x12\x17.grpc.URLCreatorRequest\x1a\x18.grpc.URLCreatorResponse\x12K\n" +
	"\x0eURLCreatorJSON\x12\x1b.grpc.URLCreatorJSONRequest\x1a\x1c.grpc.URLCreatorJSONResponse\x12N\n" +
	"\x0fURLCreatorBatch\x12\x1c.grpc.URLCreatorBatchRequest\x1a\x1d.grpc.URLCreatorBatchResponse\x12B\n" +
	"\vGetUserURLs\x12\x18.grpc.GetUserURLsRequest\x1a\x19.grpc.GetUserURLsResponse\x12K\n" +
	"\x0eDeleteUserURLs\x12\x1b.grpc.DeleteUserURLsRequest\x1a\x1c.grpc.DeleteUserURLsResponse\x129\n" +
	"\bGetStats\x12\x15.grpc.GetStatsRequest\x1a\x16.grpc.GetStatsResponseB\tZ\a./protob\x06proto3"

var (
	file_url_shortener_proto_rawDescOnce sync.Once
	file_url_shortener_proto_rawDescData []byte
)

func file_url_shortener_proto_rawDescGZIP() []byte {
	file_url_shortener_proto_rawDescOnce.Do(func() {
		file_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)))
	})
	return file_url_shortener_proto_rawDescData
}

var file_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_url_shortener_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: grpc.Empty
	(*GetURLRequest)(nil),           // 1: grpc.GetURLRequest
	(*GetURLResponse)(nil),          // 2: grpc.GetURLResponse
	(*PingResponse)(nil),            // 3: grpc.PingResponse
	(*URLCreatorRequest)(nil),       // 4: grpc.URLCreatorRequest
	(*URLCreatorResponse)(nil),      // 5: grpc.URLCreatorResponse
	(*URLCreatorJSONRequest)(nil),   // 6: grpc.URLCreatorJSONRequest
	(*URLCreatorJSONResponse)(nil),  // 7: grpc.URLCreatorJSONResponse
	(*URLRequest)(nil),              // 8: grpc.URLRequest
	(*URLResponse)(nil),             // 9: grpc.URLResponse
	(*URLCreatorBatchRequest)(nil),  // 10: grpc.URLCreatorBatchRequest
	(*URLCreatorBatchResponse)(nil), // 11: grpc.URLCreatorBatchResponse
	(*GetUserURLsRequest)(nil),      // 12: grpc.GetUserURLsRequest
	(*UserURL)(nil),                 // 13: grpc.UserURL
	(*GetUserURLsResponse)(nil),     // 14: grpc.GetUserURLsResponse
	(*DeleteUserURLsRequest)(nil),   // 15: grpc.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),  // 16: grpc.DeleteUserURLsResponse
	(*GetStatsRequest)(nil),         // 17: grpc.GetStatsRequest
	(*GetStatsResponse)(nil),        // 18: grpc.GetStatsResponse
}
var file_url_shortener_proto_depIdxs = []int32{
	8,  // 0: grpc.URLCreatorBatchRequest.requests:type_name -> grpc.URLRequest
	9,  // 1: grpc.URLCreatorBatchResponse.responses:type_name -> grpc.URLResponse
	13, // 2: grpc.GetUserURLsResponse.urls:type_name -> grpc.UserURL
	1,  // 3: grpc.URLShortener.GetURL:input_type -> grpc.GetURLRequest
	0,  // 4: grpc.URLShortener.Ping:input_type -> grpc.Empty
	4,  // 5: grpc.URLShortener.URLCreator:input_type -> grpc.URLCreatorRequest
	6,  // 6: grpc.URLShortener.URLCreatorJSON:input_type -> grpc.URLCreatorJSONRequest
	10, // 7: grpc.URLShortener.URLCreatorBatch:input_type -> grpc.URLCreatorBatchRequest
	12, // 8: grpc.URLShortener.GetUserURLs:input_type -> grpc.GetUserURLsRequest
	15, // 9: grpc.URLShortener.DeleteUserURLs:input_type -> grpc.DeleteUserURLsRequest
	17, // 10: grpc.URLShortener.GetStats:input_type -> grpc.GetStatsRequest
	2,  // 11: grpc.URLShortener.GetURL:output_type -> grpc.GetURLResponse
	3,  // 12: grpc.URLShortener.Ping:output_type -> grpc.PingResponse
	5,  // 13: grpc.URLShortener.URLCreator:output_type -> grpc.URLCreatorResponse
	7,  // 14: grpc.URLShortener.URLCreatorJSON:output_type -> grpc.URLCreatorJSONResponse
	11, // 15: grpc.URLShortener.URLCreatorBatch:output_type -> grpc.URLCreatorBatchResponse
	14, // 16: grpc.URLShortener.GetUserURLs:output_type -> grpc.GetUserURLsResponse
	16, // 17: grpc.URLShortener.DeleteUserURLs:output_type -> grpc.DeleteUserURLsResponse
	18, // 18: grpc.URLShortener.GetStats:output_type -> grpc.GetStatsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_url_shortener_proto_init() }
func file_url_shortener_proto_init() {
	if File_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shortener_proto_goTypes,
		DependencyIndexes: file_url_shortener_proto_depIdxs,
		MessageInfos:      file_url_shortener_proto_msgTypes,
	}.Build()
	File_url_shortener_proto = out.File
	file_url_shortener_proto_goTypes = nil
	file_url_shortener_proto_depIdxs = nil
}
